#resolver: lts-8.5
resolver: lts-8.13

extra-package-dbs: []

packages:
- '.'
- location:
    git: https://github.com/input-output-hk/cardano-sl
    commit: 97850b14ca8e6a4d0055e4f8a6a90380967263b0
  extra-dep: true
  subdirs:
      - '.'
      - core
      - update
      - infra
      - db
      - lrc
      - ssc
      - godtossing
      - txp
- location:
    git: https://github.com/serokell/time-units.git
    commit: 6c3747c1ac794f952de996dd7ba8a2f6d63bf132
  extra-dep: true
- location:
    git: https://github.com/serokell/acid-state.git
    commit: 95fce1dbada62020a0b2d6aa2dd7e88eadd7214b
  extra-dep: true
- location:
    git: https://github.com/serokell/kademlia.git
    commit: 92043c7e80e93aeb08212e8ce42c783edd9b2f80
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/plutus-prototype
    commit: e2e2711e6978002279b4d7c49cab1aff47a2fd43
  extra-dep: true
- location:
    git: https://github.com/serokell/rocksdb-haskell.git
    commit: 4dfd8d61263d78a91168e86e8005eb9b7069389e
  extra-dep: true
- location:
    git: https://github.com/thoughtpolice/hs-ed25519
    # We're waiting on next release
    commit: da4247b5b3420120e20451e6a252e2a2ca15b43c
  extra-dep: true
- location:
    git: https://github.com/input-output-hk/cardano-report-server.git
    commit: 424e4ecacdf038a01542025dd1296bd272ce770d
  extra-dep: true
- location:
    git: https://github.com/serokell/time-warp-nt.git
    commit: 52969ff1e14385a9fa0e7de1593969f8b5e52a1b
  extra-dep: true
# These two are needed for time-warp-nt
- location:
    git: https://github.com/serokell/network-transport-tcp
    commit: a6c04c35f3a1d786bc5e57fd04cf3e2a043179f3
  extra-dep: true
- location:
    git: https://github.com/serokell/network-transport
    commit: f2321a103f53f51d36c99383132e3ffa3ef1c401
  extra-dep: true
- location:
    git: https://github.com/serokell/engine.io.git
    commit: a594e402fd450f11ad60d09ddbd93db500000632
  extra-dep: true
  subdirs:
    - socket-io
    - engine-io
    - engine-io-wai
- location:
    git: https://github.com/input-output-hk/cardano-crypto
    commit: 84f8c358463bbf6bb09168aac5ad990faa9d310a
  extra-dep: true
# We're using forked version of 'swagger2' package because of bug in haddock package.
# Now we don't build Haddock-docs for this 'swagger2' package, and when that bug will
# be fixed, we'll back to Hackage-version.
- location:
    git: https://github.com/serokell/swagger2
    commit: 6cc2063e1c8da9e701f3ac95549b8a33be9605de
  extra-dep: true
# - location:
#     git: https://github.com/haskell-crypto/cryptonite.git
#     commit: 2932df9e243aa7ae7eb2b25d7c60fa77a30c6fb5
#   extra-dep: true

nix:
  shell-file: shell.nix

extra-deps:
- universum-0.4.3
- time-units-1.0.0
- serokell-util-0.1.5.0
- pvss-0.1
- base58-bytestring-0.1.0
- log-warper-1.1.2
- concurrent-extra-0.7.0.10       # not yet in lts-8
- purescript-bridge-0.10.1.0
- cryptonite-0.23
- cryptonite-openssl-0.6
- directory-1.3.1.0               # https://github.com/malcolmwallace/cpphs/issues/8
- servant-0.10                    # servant-multipart supports version servant-10 only
- servant-server-0.10             # so it triggers another dependencies to be v10
- servant-swagger-1.1.2.1
- servant-multipart-0.10
- ether-0.5.1.0
- transformers-lift-0.2.0.1

# The other dependencies that we need to revise
- UtilityTM-0.0.4
- derive-2.6.2                    # not yet in lts-8
- wreq-0.5.0.0                    # not yet in lts-8
- turtle-1.3.1                    # earlier versions don't have 'stat'
- optparse-applicative-0.13.0.0   # needed for turtle
- criterion-1.1.4.0               # older criterion doesn't like optparse-0.13
- code-page-0.1.1                 # needed for criterion
- websockets-snap-0.10.2.0
- websockets-0.9.8.2
- aeson-1.0.2.1
- engine-io-snap-1.0.4
- heist-1.0.1.0
- map-syntax-0.2.0.2
- snap-1.0.0.1
- snap-cors-1.2.11
- foundation-0.0.9
- memory-0.14.5
- writer-cps-transformers-0.1.1.3
- writer-cps-mtl-0.1.1.4

# This is for CI to pass --fast to all dependencies
apply-ghc-options: everything

flags:
  cardano-sl:
    with-explorer: True
  ether:
    disable-tup-instances: True
